export let ancientBuddhistTexts = {
  constants: {
    rootUrl: "https://www.ancient-buddhist-texts.net",
    suffixUrl: "",
    chapterConnector: "",
  },
  dn: {
    format: ["sutta"],

    links: { card: "/long/dn", all: "/dn" },
    available: [
      [16, "/Texts-and-Translations/Mahaparinibbanasuttam/index.htm"],
      [22, "/Texts-and-Translations/Satipatthana/index.htm"],
    ],
  },
  mn: {
    format: ["sutta"],

    links: { all: "/MN/MN" },
    available: [
      [26, "/Texts-and-Translations/Ariyapariyesana/index.htm"],
      [44, "/Texts-and-Translations/Culavedalla/Culavedalla.htm"],
      [62, "/Texts-and-Translations/Short-Pieces/MahaRahulovadasuttam.htm"],
      [85, "/Texts-and-Translations/Bodhirajakumara/index.htm"],
      [98, "/Texts-and-Translations/Short-Pieces/Vasetthasuttam.htm"],
      [118, "/Texts-and-Translations/Anapanasati/index.htm"],
      [119, "/Texts-and-Translations/Kayagatasati/index.htm"],
      [141, "/Texts-and-Translations/Short-Pieces/Saccavibhangasuttam.htm"],
      [142, "/Texts-and-Translations/Short-Pieces/Dakkhinavibhangasuttam.htm"],
      [146, "/Texts-and-Translations/Nandakovada/Nandakovada.htm"],
    ],
  },
  sn: {
    format: ["chapter"],
    links: { card: "/linked/sn", all: "/sn" },
    available: [],
  },

  an: {
    format: ["chapter"],
    links: { card: "/numbered/an", all: "/an" },
    available: [],
  },

  kn: {
    format: ["sutta"],
    links: { card: "/minor/kn", all: "/kn" },
    available: [],
  },
  kp: {
    format: ["sutta"],
    links: { all: "/KN/Khp/khp" },
    available: [
      [1, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [2, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [3, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [4, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [5, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [6, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [7, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [8, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
      [9, "/Texts-and-Translations/Khuddakapatha/Khuddakapatha.htm"],
    ],
  },
  dhp: {
    format: ["verse", "chapter"],
    links: { card: "/minor/dhp", all: "/dhp" },
    available: [],
  },
  ud: {
    format: ["chapter", "sutta"],
    links: { card: "/minor/kn/ud", all: "/ud" },
    complete: true,
    available: {
      1: [
        [1, "/Texts-and-Translations/Udana/1-Bodhivaggo-01.htm", "Pathamabodhisuttaṁ"],
        [2, "/Texts-and-Translations/Udana/1-Bodhivaggo-02.htm", "Dutiyabodhisuttaṁ"],
        [3, "/Texts-and-Translations/Udana/1-Bodhivaggo-03.htm", "Tatiyabodhisuttaṁ"],
        [4, "/Texts-and-Translations/Udana/1-Bodhivaggo-04.htm", "Nigrodhasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/1-Bodhivaggo-05.htm", "Therasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/1-Bodhivaggo-06.htm", "Kassapasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/1-Bodhivaggo-07.htm", "Pāvāsuttaṁ"],
        [8, "/Texts-and-Translations/Udana/1-Bodhivaggo-08.htm", "Saṅgāmajīsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/1-Bodhivaggo-09.htm", "Jaṭilasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/1-Bodhivaggo-10.htm", "Bāhiyasuttaṁ"],
      ],
      2: [
        [1, "/Texts-and-Translations/Udana/2-Mucalindavaggo-01.htm", "Mucalindasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/2-Mucalindavaggo-02.htm", "Rājasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/2-Mucalindavaggo-03.htm", "Daṇḍasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/2-Mucalindavaggo-04.htm", "Sakkārasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/2-Mucalindavaggo-05.htm", "Upāsakasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/2-Mucalindavaggo-06.htm", "Gabhinīsuttaṁ"],
        [7, "/Texts-and-Translations/Udana/2-Mucalindavaggo-07.htm", "Ekaputtasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/2-Mucalindavaggo-08.htm", "Suppavāsāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/2-Mucalindavaggo-09.htm", "Visākhāsuttaṁ"],
        [10, "/Texts-and-Translations/Udana/2-Mucalindavaggo-10.htm", "Bhaddiyasuttaṁ"],
      ],
      3: [
        [1, "/Texts-and-Translations/Udana/3-Nandavaggo-01.htm", 1, "Kammasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/3-Nandavaggo-02.htm", 2, "Nandasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/3-Nandavaggo-03.htm", 3, "Yasojasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/3-Nandavaggo-04.htm", 4, "Sāriputtasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/3-Nandavaggo-05.htm", 5, "Kolitasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/3-Nandavaggo-06.htm", 6, "Pilindivacchasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/3-Nandavaggo-07.htm", 7, "Kassapasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/3-Nandavaggo-08.htm", 8, "Piṇḍapātikasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/3-Nandavaggo-09.htm", 9, "Sippasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/3-Nandavaggo-10.htm", 10, "Lokavolokanasuttaṁ"],
      ],
      4: [
        [1, "/Texts-and-Translations/Udana/4-Meghiyavaggo-01.htm", "Meghiyasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/4-Meghiyavaggo-02.htm", "Uddhatasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/4-Meghiyavaggo-03.htm", "Gopālasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/4-Meghiyavaggo-04.htm", "Juṇhasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/4-Meghiyavaggo-05.htm", "Nāgasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/4-Meghiyavaggo-06.htm", "Piṇḍolasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/4-Meghiyavaggo-07.htm", "Sāriputtasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/4-Meghiyavaggo-08.htm", "Sundarīsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/4-Meghiyavaggo-09.htm", "Upasenasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/4-Meghiyavaggo-10.htm", "Sāriputtasuttaṁ"],
      ],
      5: [
        [1, "/Texts-and-Translations/Udana/5-Sonavaggo-01-01.htm", "Rājasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/5-Sonavaggo-01-02.htm", "Appāyukasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/5-Sonavaggo-01-03.htm", "Suppabuddhakuṭṭhisuttaṁ"],
        [4, "/Texts-and-Translations/Udana/5-Sonavaggo-01-04.htm", "Kumārakasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/5-Sonavaggo-01-05.htm", "Uposathasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/5-Sonavaggo-01-06.htm", "Soṇasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/5-Sonavaggo-01-07.htm", "Revatasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/5-Sonavaggo-01-08.htm", "Ānandasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/5-Sonavaggo-01-09.htm", "Saddhāyamānasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/5-Sonavaggo-01-10.htm", "Panthakasuttaṁ"],
      ],
      6: [
        [1, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-01.htm", "Āyusaṅkhāravossajanasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-02.htm", "Jaṭilasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-03.htm", "Paccavekkhanasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-04.htm", "Paṭhamanānātitthiyasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-05.htm", "Dutiyanānātitthiyasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-06.htm", "Tatiyanānātitthiyasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-07.htm", "Subhūtisuttaṁ"],
        [8, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-08.htm", "Gaṇikāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-09.htm", "Upātisuttaṁ"],
        [10, "/Texts-and-Translations/Udana/6-Jaccandhavaggo-10.htm", "Tathāgatuppādasuttaṁ"],
      ],
      7: [
        [1, "/Texts-and-Translations/Udana/7-Cullavaggo-01.htm", "Paṭhamabhaddiyasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/7-Cullavaggo-02.htm", "Dutiyabhaddiyasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/7-Cullavaggo-03.htm", "Sattasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/7-Cullavaggo-04.htm", "Dutiyasattasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/7-Cullavaggo-05.htm", "Lakuṇṭakabhaddiyasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/7-Cullavaggo-06.htm", "Taṇhākkhayasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/7-Cullavaggo-07.htm", "Papañcakkhayasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/7-Cullavaggo-08.htm", "Kaccānasuttaṁ"],
        [9, "/Texts-and-Translations/Udana/7-Cullavaggo-09.htm", "Udapānasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/7-Cullavaggo-10.htm", "Udenasuttaṁ"],
      ],
      8: [
        [1, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-01.htm", "Paṭhamanibbānasuttaṁ"],
        [2, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-02.htm", "Dutiyanibbānasuttaṁ"],
        [3, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-03.htm", "Tatiyanibbānasuttaṁ"],
        [4, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-04.htm", "Catutthanibbānasuttaṁ"],
        [5, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-05.htm", "Cundasuttaṁ"],
        [6, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-06.htm", "Pāṭaligāmiyasuttaṁ"],
        [7, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-07.htm", "Dvidhāpathasuttaṁ"],
        [8, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-08.htm", "Visākhāsuttaṁ"],
        [9, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-09.htm", "Paṭhamadabbasuttaṁ"],
        [10, "/Texts-and-Translations/Udana/8-Pataligamiyavaggo-10.htm", "Dutiyadabbasuttaṁ"],
      ],
    },
  },
  iti: {
    format: ["sutta", "chapter"],
    links: { card: "/minor/kn/iti", all: "/iti" },
    available: [],
  },
  snp: {
    format: ["chapter"],
    links: { card: "/minor/kn/snp", all: "/snp" },
    available: [],
  },
  vv: {
    format: ["sutta", "chapter"],
    links: { card: "/minor/kn/vv", all: "/vv" },
    available: [],
  },
  pv: {
    format: ["sutta", "chapter"],
    links: { card: "/minor/kn/pv", all: "/pv" },
    available: [],
  },
  thag: {
    format: ["verse", "chapter"],
    links: { card: "/minor/kn/thig", all: "/thig" },
    available: [],
  },
  thig: {
    format: ["verse", "chapter"],
    links: { card: "/minor/kn/thig", all: "/thig" },
    available: [],
  },
};
